# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20170721_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
