# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='detailed_forcast',
            new_name='detailed_forecast',
        ),
    ]
